(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.html?$'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsp$'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb$" . web-mode))
(setq web-mode-markup-indent-offset 2)
